INSERT INTO Category (CategoryName) VALUES ('Processor');
INSERT INTO Category (CategoryName) VALUES ('Graphics Card');
INSERT INTO Category (CategoryName) VALUES ('Memory');
INSERT INTO Category (CategoryName) VALUES ('Power Supply');
INSERT INTO Category (CategoryName) VALUES ('Hard Drive');
INSERT INTO Category (CategoryName) VALUES ('SSD');
INSERT INTO Category (CategoryName) VALUES ('Motherboard');
INSERT INTO Category (CategoryName) VALUES ('Cooler');
INSERT INTO Category (CategoryName) VALUES ('Video Card');
INSERT INTO Category (CategoryName) VALUES ('Keyboard');
INSERT INTO Category (CategoryName) VALUES ('Mouse');
INSERT INTO Category (CategoryName) VALUES ('Monitor');
INSERT INTO Category (CategoryName) VALUES ('Sound Card');
INSERT INTO Category (CategoryName) VALUES ('Computer Case');
INSERT INTO Category (CategoryName) VALUES ('Network Card');
INSERT INTO Category (CategoryName) VALUES ('Operating System');
INSERT INTO Category (CategoryName) VALUES ('Display');
INSERT INTO Category (CategoryName) VALUES ('Router');
INSERT INTO Category (CategoryName) VALUES ('Modem');
INSERT INTO Category (CategoryName) VALUES ('Printer');
INSERT INTO Category (CategoryName) VALUES ('Scanner');
INSERT INTO Category (CategoryName) VALUES ('Webcam');
INSERT INTO Category (CategoryName) VALUES ('Microphone');
INSERT INTO Category (CategoryName) VALUES ('Speakers');
